//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int id { get; set; }
        public string slug { get; set; }
        public string content { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public bool meno { get; set; }
        public string excerpt { get; set; }
        public string image { get; set; }
        public string gallery { get; set; }
    }
}
