//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public int id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string maincat { get; set; }
        public string topcat { get; set; }
        public string description { get; set; }
        public string topcat2 { get; set; }
        public string image { get; set; }
        public string fbimage { get; set; }
        public Nullable<int> priority { get; set; }
        public bool heureka { get; set; }
        public bool heurekadarcek { get; set; }
        public string heurekadarcektext { get; set; }
        public string heurekacat { get; set; }
        public string heurekacatname { get; set; }
        public int ordering { get; set; }
        public bool deleted { get; set; }
    }
}
