//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_settings
    {
        public int id { get; set; }
        public string companyname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string ico { get; set; }
        public string dic { get; set; }
        public string icdph { get; set; }
        public string accountnumber { get; set; }
        public string transfer1 { get; set; }
        public string transfer2 { get; set; }
        public string transfer3 { get; set; }
        public string transfer4 { get; set; }
        public string transfer5 { get; set; }
        public string pay1 { get; set; }
        public bool pay1_enbl { get; set; }
        public string pay2 { get; set; }
        public bool pay2_enbl { get; set; }
        public string pay3 { get; set; }
        public bool pay3_enbl { get; set; }
        public string pay4 { get; set; }
        public bool pay4_enbl { get; set; }
        public bool transfer1_enbl { get; set; }
        public bool transfer2_enbl { get; set; }
        public bool transfer3_enbl { get; set; }
        public bool transfer4_enbl { get; set; }
        public string custom { get; set; }
        public string deliveryprice1 { get; set; }
        public string deliveryprice2 { get; set; }
        public string deliveryprice3 { get; set; }
        public string vopPdf { get; set; }
        public string returnPdf { get; set; }
    }
}
