//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordermeta
    {
        public int id { get; set; }
        public string ordernumber { get; set; }
        public string product { get; set; }
        public string productid { get; set; }
        public string pieces { get; set; }
        public string productimage { get; set; }
        public decimal price { get; set; }
        public string variant { get; set; }
        public string variant2 { get; set; }
        public bool deleted { get; set; }
    }
}
