//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string number { get; set; }
        public bool recommended { get; set; }
        public string stock { get; set; }
        public string price { get; set; }
        public string date { get; set; }
        public string gallery { get; set; }
        public string category { get; set; }
        public string weight { get; set; }
        public string weightunit { get; set; }
        public string description { get; set; }
        public string discountprice { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
    }
}
