//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class settings
    {
        public int id { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public Nullable<int> indexed { get; set; }
        public string googleanalyt { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string adress { get; set; }
        public string psc { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
    }
}
