//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slideshow
    {
        public int id { get; set; }
        public string page { get; set; }
        public string image { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string header { get; set; }
        public string text { get; set; }
        public string subtext { get; set; }
        public string button { get; set; }
        public int active { get; set; }
    }
}
