//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersmeta
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string companyname { get; set; }
        public string ico { get; set; }
        public string dic { get; set; }
        public string icdph { get; set; }
        public bool news { get; set; }
        public bool gdpr { get; set; }
    }
}
