//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userstoken
    {
        public int id { get; set; }
        public string email { get; set; }
        public string token { get; set; }
        public string type { get; set; }
        public string time { get; set; }
    }
}
